import './globals.css'
import type { Metadata } from 'next'
import {Rubik} from 'next/font/google'


const rubikFont = Rubik({
    weight: ["400", "600"],
    subsets: ["cyrillic", "hebrew", "latin"],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


interface Props {
    children: React.ReactNode
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
        <body className={`${rubikFont.className} min-h-screen w-screen flex flex-col overflow-x-hidden antialiased`}>
            <div className="flex-grow">
                {children}
            </div>
        </body>
    </html>
  )
}
